### ISSUE TITLE
Categories action

### ISSUE THREAD

**Issue by Kyun92** [logostory/orderbook-frontend#13]
카테고리 액션 && 디자인 적용

**Comment by Kyun92** [comment]
# 카테고리 작업 과정에서 이슈 - 181212

## 😂 Scroll spy

Scroll spy 기능은 현재 방법을 찾고 있습니다. [react-scroll](https://www.npmjs.com/package/react-scroll)를 이용하면 해결 할 수 있을 것 같은데, 오늘은 다른 작업이 material ui 적용을 우선으로 했습니다.

## 👏 Redux 적용

### `/modules/menu.js`

추가하였습니다. 전 `handleActions`와 `createAction`을 이용하는게 익숙해져서 두 모듈을 사용했습니다.

@gyutaesi 님의 Dialogs작업할때 메뉴 클릭 액션이 필요할 것 같아 `CLICK_MENU` 액션을 생성해놨습니다.
payload는 `productId`를 받아옵니다.
현재는 그냥 `console.log(productId)`입니다.

### `/componets/Category && Menu` 추가

기존에 `/containers/menu`에 있던 컴포넌트들을 분리했습니다.

### `/containers/menu/MenuContainer.js`

@gyutaesi  `CLICK_MENU` 액션을 `handleClickMenu` 함수로 호출합니다. 해당부분은 주석을 달아놨습니다.

`connect` 와 `bindActionCreators`을 사용해 작성했습니다. 문제가 된다면 순수 형태로 변경하겠습니다.

## 🙏 menuComment 요청

menu List 그릴때 메뉴설명이 디자인에 추가가 되었고 이에 따라 Backend 팀에게 `products` 객체에 `menuComment`를 요청했습니다.

## ✍️ Material UI 적용

제플린에 올라온 디자인에 맞게 Material UI를 적용했습니다.

### 👾 Tabs font color not work...

이 과정에서 유일하게 문제가 되었던 부분은 Tab이 active 됐을때의 폰트 색상이 변경이 안됩니다. 밑의 줄 표시는 색상이 변경 되지만, 이 부분은 적용이 안되어 헤매고 있습니다.

이 부분 아시는 분 도움을 주시면 감사하겠습니다..

**Comment by nambiho** [comment]
Tab Component에 selected classes를 적용 해보세요.
<Tab classes={{selected: classes.selected}} .../>

**Comment by seongbin9786** [comment]
PR 넣어주세요!
