### ISSUE TITLE
Github Pages로 호스팅 시에 SPA routing이 안 됨

### ISSUE THREAD

**Issue by seongbin9786** [logostory/orderbook-frontend#20]
React-router 기반의 SPA 라우팅이 github pages에서 작동하지 않는 것 같습니다.

**확인 가능한 예제** 
1. Payment: https://orderbook.logostory.io/payment
2. Cart: https://orderbook.logostory.io/cart

**원본 코드**
```js
<BrowserRouter>
    <Switch>
        <Route exact path="/" component={Loading} />
        <Route path="/basic" component={BasicPage} />
        <Route path="/cart" component={CartPage} /> 
        <Route path="/payment" component={Payment} />
    </Switch>
</BrowserRouter>
```

**Comment by torypapa** [comment]
이거 한번 확인 해보시겠어요? https://github.com/facebook/create-react-app/issues/1765

https://github.com/facebook/create-react-app/issues/1765#issuecomment-285114194 @gaearon  이라는 친구가 대답해 놓은게 답이 될듯한데요

**Comment by seongbin9786** [comment]
👍

**Comment by seongbin9786** [comment]
일단 HashRouter로 됐고 현재 더 이상 큰 문제가 없으므로 이슈를 닫습니다~
