### ISSUE TITLE
A10(주문 완료) 페이지 구현

### ISSUE THREAD

**Issue by polycompo** [logostory/orderbook-frontend#28]
**해당 화면에 대한 상세설명**
해당 화면은 `A9(결제화면)`에서 결제가 완료가 되었을 때 나타나는 화면
해당 화면 음영구역 뒤에는 `A5(메뉴화면)`이 나와야 됨
-> 해당 화면은 page로 작성해야됨
-> confirm을 누르면 `A5(메뉴화면)`화면으로 이동됨

**해당 화면을 구현하는데 어떤 부수효과가 예상됩니까?**
x

**해당 화면을 구현하는데 필요사항이 있습니까?**
1. order 넘버링을 받아오는 방식이 서버와 통신을 해야되는지 확인이 필요합니다.
2. order confirm을 눌렀을 경우 매장의 메뉴화면으로 이동하게 되는데, 현재 confirm이 된 오더(주문내역)을 확인 할 수 있는 화면이 있나요?

**Comment by polycompo** [comment]
ordering은 props로 넘겨 받을 예정
route url구성은 ```/order```로 구성할 예정

**Comment by polycompo** [comment]
브랜치 : f#28-create_order_confirm_page

**Comment by polycompo** [comment]
외부에서 접근한 url일 경우 `A3` 페이지가 떠야된다.

**Comment by seongbin9786** [comment]
👍

**Comment by seongbin9786** [comment]
Related to #52

**Comment by polycompo** [comment]
A10페이지로 요청을 보낼때 URL
```/order/number={id}```
